devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: 828798e2-2fc6-4df1-9901-5b527a364603
images:
    debug: ''
    release: ''
imagetags:
    debug: pythonforms_arm32v7-debian-python3-qt_bullseye_debug_828798e2-2fc6-4df1-9901-5b527a364603
    release: pythonforms_arm32v7-debian-python3-qt_bullseye_release_828798e2-2fc6-4df1-9901-5b527a364603
modificationdate: '2022-08-15T21:42:37.499739'
networks:
    common: []
    debug: []
    release: []
otapackagename: ''
otapackageversion: 1.0.0
platformid: arm32v7-debian-python3-qt_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEAo+rpp8odi22Q4RdJnzfit9dI3o+1N/dBhVxE+dzF1cNmbEA7

    gHgRtBGrSJFJtQk+vc0sLIkeUAkO1bx0F6WT/gXY0JIyXvXvHKwmjGLbTgFOk8U3

    ZmJymhaMHvKSycsO33GhbbTV+N8Eorv1cKmu6SGi5JuexSbmRgy6XzidHO9pztny

    GMjyLSSKabkBr+0v7iQohhNHJe56aAMmsRmZtolO3gdkWmrnTaqQZhrN/9078nVO

    OWx+n4NA6TxeQta1AX6fnQhk1SZrxFISTHchoVSZiJU71zWxrO5Opsn+xcotWdky

    hmSeVbNKrjoMP92et/I4jdpA0SnXTOLzWSIOBwIDAQABAoIBAAlAWqMVIBJTnnf6

    XaOokPTr3svaD2ROYezg9EqDmaSQqiIQzgHGMsdOZ/z7X2B0WkR2ZSYlMCzJ8YPU

    Zn/WBbBEme05XEQlgLMPSySJP89o+TATnEshT+DRWGPJC+60R8jl0qBRV1/76J1b

    P4njt4U46n3QA9Vt5AuKXYFRK4hUvOPahyP/+uldQpsA1Dx6usR6PAB6V/s74Ah1

    EARet4tueVdmQfbTTb4pPZVjWHtXAP+SdZvQLRbuzOwT672p6L3xsu5O8MLpDg8I

    TwPdYZ+RthMEo7WYpOKz9NN0OBLnHCBlhdJPGckRyQ6PonFq/S+gIYgfir8g8zCd

    gv8hXSECgYEAzAax2+68aN+IjjriSOKo5c49IUGUXO/GsU0z7dexWgyI3xWQyeC0

    2I7UZGzuwVBRd1v9inX7PhRzIofbWgUn29h969Qkf4Xd7DLLi03ckSIZIzjK3Dw+

    wSpoYgnNpevJs0SGP7heKmPoBUK/h5ViwDv1bUI24G3xK+m0FoAuPRMCgYEAzayX

    fIACkPYxwkPg3AdHB+9ivmOTubHLkZg450eFFfMRJuIohMRpDl4DHfMEaSm1Y7Zh

    u7xl1s/EWl/lmNXK4VFAtf+70Wg7Qu8XsDFHK+XeQBRHg+AINXMAUjcxkrF7L2jb

    FJdYJ4Y2EHCclFVj6KAppD48Y+ubYZl5hLAnDb0CgYBKVSIVs+wW9WHmF9P7pADP

    AQ3KgP8RwRYN4MfLnqrx2OFBDbVbp6+buqXtFLcD3URhDTXZbVSk8IRmD0M+j+RO

    t5hhBEBr6ZTKClOYJDz474hjCbz28kgWzmGLXnD7Q2WQF6YlrwE3xoBw8jmfpzB8

    QxwOu3IM4GFek13WWMr/2wKBgQCIpPMcJxwNXVPfwiMha8BYWEXdQeECjUo3F9Au

    cEjONWge0kCjPK6jefhOLIewqqI1dhVmmht65RyKAo5SxS9+FPKOODJ7ROmiZaDy

    UTr8wkKvhgmhZvVtNVNwS/Umhb3W2K489vP9hmBi+b49mqG/CrG/yg1rQTxBUqr2

    aeX4bQKBgBceNqIL6qyemD6wqvG3dU9fEc0bLLrQPNfcRmMFasXUhb8PUmfoAlYe

    GWNr1K32mwepdDeBIxKr1VR0/RCcpQrZL/QC8PwkW+QOVGYtId1xOaqbMsqmaO1Q

    HNeiByfzrT7Eu7nEZbbZ1YthXfXIDWOiX+GjEv31TFzjZnF1x9UH

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appargs: ''
        appname: pythonForms
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        expose: ''
        extrapackages: ''
        language: python
        main: main.py
        preinstallcommands: ''
        runtime: python3
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj6umnyh2LbZDhF0mfN+K310jej7U390GFXET53MXVw2ZsQDuAeBG0EatIkUm1CT69zSwsiR5QCQ7VvHQXpZP+BdjQkjJe9e8crCaMYttOAU6TxTdmYnKaFowe8pLJyw7fcaFttNX43wSiu/Vwqa7pIaLkm57FJuZGDLpfOJ0c72nO2fIYyPItJIppuQGv7S/uJCiGE0cl7npoAyaxGZm2iU7eB2RaaudNqpBmGs3/3TvydU45bH6fg0DpPF5C1rUBfp+dCGTVJmvEUhJMdyGhVJmIlTvXNbGs7k6myf7Fyi1Z2TKGZJ5Vs0quOgw/3Z638jiN2kDRKddM4vNZIg4H
sdkimages:
    debug: ''
    release: ''
sdkimagetags:
    debug: ''
    release: ''
sdksshaddress:
    debug: null
    release: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common: {}
    debug: {}
    release: {}
